# Generated by Django 3.1.5 on 2021-01-31 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'account(for login)',
                'ordering': ['user_name'],
            },
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.user_account')),
                ('nick_name', models.TextField(blank=True, max_length=2)),
                ('position', models.TextField(blank=True, max_length=10)),
                ('self_introduction', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'account(for information)',
                'ordering': ['user'],
            },
        ),
    ]
